studyroom:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: study_room_reservation
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0
  wechat:
    appid: wx8e39b2063ff7139b
    secret: 6b4da0f3e83b519790d021591c1d41ca
  chat:
    base-url: https://api.example.com/v1
    api-key: your-api-key
    model: gpt-3.5-turbo

  upload:
    path: c:/Users/javapython/Desktop/zzzxs01/study-room-reservation/studyroom-server/upload
